# Generated by Django 3.0.3 on 2020-03-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200307_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portf',
            name='phoneno',
            field=models.BigIntegerField(blank=True),
        ),
    ]
