# Generated by Django 3.0.3 on 2020-03-08 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200307_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='portf',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
