# Generated by Django 3.0.3 on 2020-03-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_portf_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portf',
            name='skills',
            field=models.CharField(max_length=200),
        ),
    ]
